apiVersion: sample.template.crossplane.io/v1alpha1
kind: MyType
metadata:
  name: myexample
spec:
  forProvider:
    configurableField: myTest
    otherConfigurableFieldRef:
      name: otherexample
  providerConfigRef:
    name: example
---
apiVersion: sample.template.crossplane.io/v1alpha1
kind: OtherType
metadata:
  name: otherexample
spec:
  forProvider:
    configurableField: otherTest
  providerConfigRef:
    name: example
---
apiVersion: sample.template.crossplane.io/v1alpha1
kind: SomeType
metadata:
  name: someexample
spec:
  forProvider:
    configurableField: someTest
  providerConfigRef:
    name: example
